[book]
authors = ["Federico 'Morg' Pareschi"]
language = "en"
multilingual = false
src = "src"
title = "Yokubi"

[output.html]
default-theme = "Navy"
additional-css = ["custom.css"]
no-section-label = true
