[book]
authors = ["Morg"]
language = "ja"
src = "src"
title = "Yokubi"

[output.html]
default-theme = "Navy"
additional-css = ["style/custom.css"]
no-section-label = true

[output.html.fold]
enable = true
